"""Summarize the agents NOT picked into HANDOFF.md.

Per mainai.md step 4: extract per-session facts without an LLM (prompts,
final answers, files touched, commands run), then have one LLM call condense
all of that into a single handoff document. One call covers every "other"
session so cost doesn't scale per session.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

from mainai import llm
from mainai.models import Session

MAX_TURN_CHARS = 600
HEAD_TURNS = 3
TAIL_TURNS = 5

HANDOFF_FILENAME = "HANDOFF.md"


def write_handoff(
    sessions: list[Session],
    chosen: Session,
    folder: Path,
    only_agents: set[str] | None = None,
) -> Path:
    """Write HANDOFF.md summarizing sessions.

    By default (`only_agents=None`), every session other than `chosen` is
    summarized. When `only_agents` is given, sessions are selected purely by
    agent name -- including `chosen` itself if its agent is in the set.
    That's intentional: "continue with grok" launches a fresh `grok`
    process in the folder, it doesn't resume `chosen` specifically, so even
    grok's own prior session is useful context for that fresh conversation.
    """
    if only_agents is not None:
        others = [s for s in sessions if s.agent in only_agents]
    else:
        others = [s for s in sessions if s is not chosen]

    if not others:
        if only_agents is not None:
            raise ValueError(
                f"no sessions found for agent(s) {', '.join(sorted(only_agents))} "
                "in this folder"
            )
        raise ValueError("only one session found; nothing to hand off")

    body = llm.call(_build_prompt(others, chosen, folder), timeout=240).strip()
    summarized_agents = ", ".join(sorted({s.agent for s in others}))
    header = (
        f"<!-- Generated by mainai on {datetime.now(timezone.utc).isoformat()} -->\n"
        f"# Handoff for {folder}\n\n"
        f"Continuing with **{chosen.agent}** "
        f"(session `{chosen.session_id}`, last active {chosen.end.date()}).\n"
        f"Summarized from {len(others)} session(s): {summarized_agents}.\n\n"
    )

    path = Path(folder) / HANDOFF_FILENAME
    path.write_text(header + body + "\n", encoding="utf-8")
    return path


def _session_extract(session: Session) -> dict:
    turns = [t for t in session.turns if t.text.strip()]
    if len(turns) > HEAD_TURNS + TAIL_TURNS:
        kept = turns[:HEAD_TURNS] + turns[-TAIL_TURNS:]
        omitted = len(turns) - len(kept)
    else:
        kept = turns
        omitted = 0

    turn_lines = [f"{t.role}: {t.text[:MAX_TURN_CHARS]}" for t in kept]
    if omitted:
        turn_lines.insert(HEAD_TURNS, f"... [{omitted} turn(s) omitted] ...")

    return {
        "agent": session.agent,
        "session_id": session.session_id,
        "date": session.end.date().isoformat(),
        "start": session.start.isoformat(),
        "end": session.end.isoformat(),
        "title": session.title,
        "files_touched": sorted(session.files_touched),
        "commands_run": session.commands_run[:20],
        "turns": turn_lines,
    }


def _build_prompt(others: list[Session], chosen: Session, folder: Path) -> str:
    data = [_session_extract(s) for s in others]
    chosen_included = any(s is chosen for s in others)
    if chosen_included:
        continuing_note = (
            f"The developer will continue by launching a fresh '{chosen.agent}' "
            f"process in the folder -- it won't remember any prior session, "
            f"including its own, so one of the sessions below IS a prior "
            f"'{chosen.agent}' session; summarize it like any other."
        )
    else:
        continuing_note = (
            f"The developer will continue with '{chosen.agent}', picking up "
            "from its most recent session there; do NOT summarize that "
            "session, it's not included below."
        )
    return (
        "A developer is about to continue work on a project folder using the "
        f"coding agent '{chosen.agent}'. {continuing_note} Below are extracts "
        "of sessions in the same folder useful as context. Condense them into "
        "a single handoff document so the developer (and the agent, if shown "
        "this file) can quickly catch up on what happened in those sessions.\n\n"
        f"Project folder: {folder}\n"
        f"Continuing with: {chosen.agent}\n\n"
        "Sessions to summarize (JSON):\n"
        f"{json.dumps(data, indent=2)}\n\n"
        "Write the handoff as Markdown with exactly these section headings, in "
        "this order: `## Goal`, `## Done`, `## Decisions`, `## Open items`, "
        "`## Gotchas`, `## Key files`. Tag each bullet with the agent name and "
        "date it came from, like `- (codex, 2026-09-28) ...`. Be concise: "
        "bullets, not prose. Omit a section entirely if there's nothing to put "
        "in it. Reply with ONLY the Markdown document -- no preamble, no code "
        "fence around it."
    )
